2022-04-22 11:00:41,541 INFO    MainThread:93819 [wandb_setup.py:_flush():75] Loading settings from /share/etud/e2008984/.config/wandb/settings
2022-04-22 11:00:41,541 INFO    MainThread:93819 [wandb_setup.py:_flush():75] Loading settings from /share/mastoc/projects/erasmus/dl_historical_images/master_thesis/utils/wandb/settings
2022-04-22 11:00:41,542 INFO    MainThread:93819 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-04-22 11:00:41,542 INFO    MainThread:93819 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-04-22 11:00:41,542 INFO    MainThread:93819 [wandb_init.py:_log_setup():405] Logging user logs to /share/mastoc/projects/erasmus/dl_historical_images/master_thesis/utils/wandb/run-20220422_110041-i3fusgss/logs/debug.log
2022-04-22 11:00:41,542 INFO    MainThread:93819 [wandb_init.py:_log_setup():406] Logging internal logs to /share/mastoc/projects/erasmus/dl_historical_images/master_thesis/utils/wandb/run-20220422_110041-i3fusgss/logs/debug-internal.log
2022-04-22 11:00:41,542 INFO    MainThread:93819 [wandb_init.py:init():439] calling init triggers
2022-04-22 11:00:41,542 INFO    MainThread:93819 [wandb_init.py:init():442] wandb.init called with sweep_config: {}
config: {}
2022-04-22 11:00:41,542 INFO    MainThread:93819 [wandb_init.py:init():458] re-initializing run, found existing run on stack: 1bc5j9uf
2022-04-22 11:00:41,543 INFO    MainThread:93819 [wandb_run.py:finish():1539] finishing run vibferreira/master_thesis/1bc5j9uf
2022-04-22 11:00:41,543 INFO    MainThread:93819 [jupyter.py:save_history():429] not saving jupyter history
2022-04-22 11:00:41,543 INFO    MainThread:93819 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-04-22 11:00:41,543 INFO    MainThread:93819 [wandb_init.py:_jupyter_teardown():337] cleaning up jupyter logic
2022-04-22 11:00:41,544 INFO    MainThread:93819 [wandb_run.py:_atexit_cleanup():1702] got exitcode: 0
2022-04-22 11:00:41,547 INFO    MainThread:93819 [wandb_run.py:_restore():1674] restore
2022-04-22 11:00:42,026 INFO    MainThread:93819 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
  media_count: 300
}
pusher_stats {
  uploaded_bytes: 10605631
  total_bytes: 10605631
}

2022-04-22 11:00:42,275 INFO    MainThread:93819 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
  media_count: 300
}
pusher_stats {
  uploaded_bytes: 10605631
  total_bytes: 10605631
}

2022-04-22 11:00:42,766 INFO    MainThread:93819 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
  media_count: 300
}
pusher_stats {
  uploaded_bytes: 10605631
  total_bytes: 10612299
}

2022-04-22 11:00:42,869 INFO    MainThread:93819 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
  media_count: 300
}
pusher_stats {
  uploaded_bytes: 10605631
  total_bytes: 10612299
}

2022-04-22 11:00:42,972 INFO    MainThread:93819 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
  media_count: 300
}
pusher_stats {
  uploaded_bytes: 10612299
  total_bytes: 10612299
}

2022-04-22 11:00:43,076 INFO    MainThread:93819 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
  media_count: 300
}
pusher_stats {
  uploaded_bytes: 10612299
  total_bytes: 10612299
}

2022-04-22 11:00:43,178 INFO    MainThread:93819 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
  media_count: 300
}
pusher_stats {
  uploaded_bytes: 10612299
  total_bytes: 10612299
}

2022-04-22 11:00:43,281 INFO    MainThread:93819 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
  media_count: 300
}
pusher_stats {
  uploaded_bytes: 10612299
  total_bytes: 10612299
}

2022-04-22 11:00:43,383 INFO    MainThread:93819 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
  media_count: 300
}
pusher_stats {
  uploaded_bytes: 10612299
  total_bytes: 10612299
}

2022-04-22 11:00:43,486 INFO    MainThread:93819 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
  media_count: 300
}
pusher_stats {
  uploaded_bytes: 10612299
  total_bytes: 10612299
}

2022-04-22 11:00:44,327 INFO    MainThread:93819 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
  media_count: 300
}
pusher_stats {
  uploaded_bytes: 10612299
  total_bytes: 10612299
}

2022-04-22 11:00:44,781 INFO    MainThread:93819 [wandb_run.py:_on_finish():1831] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
  media_count: 300
}
pusher_stats {
  uploaded_bytes: 10612299
  total_bytes: 10612299
}
local_info {
}

2022-04-22 11:00:46,116 INFO    MainThread:93819 [wandb_run.py:_footer_history_summary_info():2865] rendering history
2022-04-22 11:00:46,117 INFO    MainThread:93819 [wandb_run.py:_footer_history_summary_info():2894] rendering summary
2022-04-22 11:00:46,160 INFO    MainThread:93819 [wandb_run.py:_footer_sync_info():2822] logging synced files
2022-04-22 11:00:46,165 INFO    MainThread:93819 [wandb_init.py:init():492] starting backend
2022-04-22 11:00:46,166 INFO    MainThread:93819 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-04-22 11:00:46,200 INFO    MainThread:93819 [backend.py:ensure_launched():219] starting backend process...
2022-04-22 11:00:46,267 INFO    MainThread:93819 [backend.py:ensure_launched():224] started backend process with pid: 99076
2022-04-22 11:00:46,269 INFO    MainThread:93819 [wandb_init.py:init():501] backend started and connected
2022-04-22 11:00:46,349 INFO    MainThread:93819 [wandb_run.py:_label_probe_notebook():947] probe notebook
2022-04-22 11:00:46,350 INFO    MainThread:93819 [wandb_run.py:_label_probe_notebook():957] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-04-22 11:00:46,350 INFO    MainThread:93819 [wandb_init.py:init():565] updated telemetry
2022-04-22 11:00:46,514 INFO    MainThread:93819 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-04-22 11:00:51,255 INFO    MainThread:93819 [wandb_run.py:_on_init():1759] communicating current version
2022-04-22 11:00:51,330 INFO    MainThread:93819 [wandb_run.py:_on_init():1763] got version response upgrade_message: "wandb version 0.12.15 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-04-22 11:00:51,330 INFO    MainThread:93819 [wandb_init.py:init():625] starting run threads in backend
2022-04-22 11:00:56,025 INFO    MainThread:93819 [wandb_run.py:_console_start():1733] atexit reg
2022-04-22 11:00:56,027 INFO    MainThread:93819 [wandb_run.py:_redirect():1606] redirect: SettingsConsole.WRAP
2022-04-22 11:00:56,027 INFO    MainThread:93819 [wandb_run.py:_redirect():1643] Wrapping output streams.
2022-04-22 11:00:56,029 INFO    MainThread:93819 [wandb_run.py:_redirect():1667] Redirects installed.
2022-04-22 11:00:56,029 INFO    MainThread:93819 [wandb_init.py:init():664] run started, returning control to user process
