2022-04-10 11:49:07,938 INFO    MainThread:86981 [wandb_setup.py:_flush():75] Loading settings from /share/etud/e2008984/.config/wandb/settings
2022-04-10 11:49:07,939 INFO    MainThread:86981 [wandb_setup.py:_flush():75] Loading settings from /share/mastoc/projects/erasmus/dl_historical_images/master_thesis/utils/wandb/settings
2022-04-10 11:49:07,939 INFO    MainThread:86981 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-04-10 11:49:07,939 INFO    MainThread:86981 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-04-10 11:49:07,939 INFO    MainThread:86981 [wandb_init.py:_log_setup():405] Logging user logs to /share/mastoc/projects/erasmus/dl_historical_images/master_thesis/utils/wandb/run-20220410_114907-g5glcj3a/logs/debug.log
2022-04-10 11:49:07,939 INFO    MainThread:86981 [wandb_init.py:_log_setup():406] Logging internal logs to /share/mastoc/projects/erasmus/dl_historical_images/master_thesis/utils/wandb/run-20220410_114907-g5glcj3a/logs/debug-internal.log
2022-04-10 11:49:07,939 INFO    MainThread:86981 [wandb_init.py:init():439] calling init triggers
2022-04-10 11:49:07,939 INFO    MainThread:86981 [wandb_init.py:init():442] wandb.init called with sweep_config: {}
config: {}
2022-04-10 11:49:07,939 INFO    MainThread:86981 [wandb_init.py:init():458] re-initializing run, found existing run on stack: 3s1brr4n
2022-04-10 11:49:07,940 INFO    MainThread:86981 [wandb_run.py:finish():1539] finishing run vibferreira/master_thesis/3s1brr4n
2022-04-10 11:49:07,940 INFO    MainThread:86981 [jupyter.py:save_history():429] not saving jupyter history
2022-04-10 11:49:07,940 INFO    MainThread:86981 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-04-10 11:49:07,940 INFO    MainThread:86981 [wandb_init.py:_jupyter_teardown():337] cleaning up jupyter logic
2022-04-10 11:49:07,940 INFO    MainThread:86981 [wandb_run.py:_atexit_cleanup():1702] got exitcode: 0
2022-04-10 11:49:07,944 INFO    MainThread:86981 [wandb_run.py:_restore():1674] restore
2022-04-10 11:49:08,398 INFO    MainThread:86981 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
  media_count: 160
}
pusher_stats {
  uploaded_bytes: 4594050
  total_bytes: 4594050
}

2022-04-10 11:49:08,631 INFO    MainThread:86981 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
  media_count: 160
}
pusher_stats {
  uploaded_bytes: 4594050
  total_bytes: 4594050
}

2022-04-10 11:49:08,830 INFO    MainThread:86981 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
  media_count: 160
}
pusher_stats {
  uploaded_bytes: 4594050
  total_bytes: 4601539
}

2022-04-10 11:49:08,933 INFO    MainThread:86981 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
  media_count: 160
}
pusher_stats {
  uploaded_bytes: 4594050
  total_bytes: 4601539
}

2022-04-10 11:49:09,035 INFO    MainThread:86981 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
  media_count: 160
}
pusher_stats {
  uploaded_bytes: 4596609
  total_bytes: 4601539
}

2022-04-10 11:49:09,139 INFO    MainThread:86981 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
  media_count: 160
}
pusher_stats {
  uploaded_bytes: 4601539
  total_bytes: 4601539
}

2022-04-10 11:49:09,242 INFO    MainThread:86981 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
  media_count: 160
}
pusher_stats {
  uploaded_bytes: 4601539
  total_bytes: 4601539
}

2022-04-10 11:49:09,344 INFO    MainThread:86981 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
  media_count: 160
}
pusher_stats {
  uploaded_bytes: 4601539
  total_bytes: 4601539
}

2022-04-10 11:49:09,446 INFO    MainThread:86981 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
  media_count: 160
}
pusher_stats {
  uploaded_bytes: 4601539
  total_bytes: 4601539
}

2022-04-10 11:49:09,548 INFO    MainThread:86981 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
  media_count: 160
}
pusher_stats {
  uploaded_bytes: 4601539
  total_bytes: 4601539
}

2022-04-10 11:49:10,172 INFO    MainThread:86981 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
  media_count: 160
}
pusher_stats {
  uploaded_bytes: 4601539
  total_bytes: 4601539
}

2022-04-10 11:49:10,608 INFO    MainThread:86981 [wandb_run.py:_on_finish():1831] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
  media_count: 160
}
pusher_stats {
  uploaded_bytes: 4601539
  total_bytes: 4601539
}
local_info {
}

2022-04-10 11:49:11,787 INFO    MainThread:86981 [wandb_run.py:_footer_history_summary_info():2865] rendering history
2022-04-10 11:49:11,788 INFO    MainThread:86981 [wandb_run.py:_footer_history_summary_info():2894] rendering summary
2022-04-10 11:49:11,793 INFO    MainThread:86981 [wandb_run.py:_footer_sync_info():2822] logging synced files
2022-04-10 11:49:11,799 INFO    MainThread:86981 [wandb_init.py:init():492] starting backend
2022-04-10 11:49:11,799 INFO    MainThread:86981 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-04-10 11:49:11,807 INFO    MainThread:86981 [backend.py:ensure_launched():219] starting backend process...
2022-04-10 11:49:11,875 INFO    MainThread:86981 [backend.py:ensure_launched():224] started backend process with pid: 90986
2022-04-10 11:49:11,876 INFO    MainThread:86981 [wandb_init.py:init():501] backend started and connected
2022-04-10 11:49:11,908 INFO    MainThread:86981 [wandb_run.py:_label_probe_notebook():947] probe notebook
2022-04-10 11:49:11,908 INFO    MainThread:86981 [wandb_run.py:_label_probe_notebook():957] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-04-10 11:49:11,908 INFO    MainThread:86981 [wandb_init.py:init():565] updated telemetry
2022-04-10 11:49:12,021 INFO    MainThread:86981 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-04-10 11:49:13,564 INFO    MainThread:86981 [wandb_run.py:_on_init():1759] communicating current version
2022-04-10 11:49:13,625 INFO    MainThread:86981 [wandb_run.py:_on_init():1763] got version response upgrade_message: "wandb version 0.12.14 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-04-10 11:49:13,625 INFO    MainThread:86981 [wandb_init.py:init():625] starting run threads in backend
2022-04-10 11:49:14,920 INFO    MainThread:86981 [wandb_run.py:_console_start():1733] atexit reg
2022-04-10 11:49:14,921 INFO    MainThread:86981 [wandb_run.py:_redirect():1606] redirect: SettingsConsole.WRAP
2022-04-10 11:49:14,921 INFO    MainThread:86981 [wandb_run.py:_redirect():1643] Wrapping output streams.
2022-04-10 11:49:14,922 INFO    MainThread:86981 [wandb_run.py:_redirect():1667] Redirects installed.
2022-04-10 11:49:14,922 INFO    MainThread:86981 [wandb_init.py:init():664] run started, returning control to user process
